# Credits go to https://github.com/Platane/snk (go to the repo for more details)
name: Generate snake game from contribution graph

on:
  # Runs every day at 3:10 UTC
  schedule:
    - cron: "10 3 * * *"

  # Allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  generate-snk:
    runs-on: ubuntu-latest

    # Uses https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml as an example
    steps:
      # Generate a snake game SVG from my GitHub contributions graph
      - name: Generate gh-contribution-snk.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/gh-contribution-snk.svg

      - name: Push snake game SVG to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
